Fixed all norminette errors

diff --git a/42_Curriculum/Milestone_3/Codexion/Makefile b/42_Curriculum/Milestone_3/Codexion/Makefile
--- a/42_Curriculum/Milestone_3/Codexion/Makefile
+++ b/42_Curriculum/Milestone_3/Codexion/Makefile
@@ -143,6 +143,12 @@ helgrind: $(NAME)
 				echo "$(GREEN)\nNo race conditions found$(RESET)"; \
 			  fi
 
+norminette:
+	@echo "$(YELLOW)Running norminette in the 'srcs' file...\n$(RESET)"
+	@out=$$(norminette ./*) \
+		&& echo "${GREEN}✓ Norminette passed${RESET}" \
+		|| { printf '%s\n' "$$out" | grep -v ': OK!$$'; echo "${RED}\n✗ Norminette failed${RESET}"; }
+
 debug: $(DEBUGEXEC)
 	@echo "${GREEN}Debug program is compiled and ready to use !! $(DEBUGGER)...${RESET}"
 
@@ -171,4 +177,4 @@ re: fclean all
 
 re-debug: fclean debug
 
-.PHONY: help help-run all valgrind helgrind debug clean fclean re re-debug
+.PHONY: help help-run all valgrind helgrind norminette debug clean fclean re re-debug
